### ISSUE TITLE
Request to add uptime and parent_pid for win_process, win_socket and win_file_events tables

### ISSUE THREAD

**Issue by devesh10s** [eclecticiq/osq-ext-bin#10]
- [x] Not getting uptime information in below tables
        1. win_process_events 
        2. win_socket_events
        3. win_file_events

- [x] Not getting parent_pid information in below tabels
         1. win_socket_events
         2. win_file_events

**Comment by hyadav-eiq** [comment]
Thank you for writing to us. Please be ensured that we have taken a note of these requirements and will plan to add the missing information in the tables in upcoming releases. However, it is still possible to get the required information in the latest published version of EclecticIQ osquery extension 4.0.0.0 by JOINing tables in queries as provided below:

Example query to get **parent_pid** information in **win_file_events**:
----------------------------------------------------------------
select wfe.sha256, wfe.action, wfe.eid, wfe.pid, wfe.target_path, wfe.process_guid, wpe.parent_pid as parent_pid from **win_file_events** wfe JOIN **win_process_events** wpe ON (wfe.process_guid = wpe.process_guid) where wpe.action='PROC_CREATE';

Example query to get **parent_pid** information in **win_socket_events**:
------------------------------------------------------------------
select wse.action, wse.eid, wse.local_address, wse.remote_address, wse.pid, wse.process_guid, wpe.parent_pid as parent_pid from **win_socket_events** wse JOIN **win_process_events** wpe ON (wse.process_guid = wpe.process_guid) where wpe.action='PROC_CREATE';

Example query to get **uptime** information in **win_file_events**:
------------------------------------------------------------
select wfe.sha256, wfe.action, wfe.eid, wfe.pid, wfe.target_path, wfe.process_guid, ut.total_seconds AS uptime from **win_file_events** wfe JOIN **uptime** ut;

Example query to get **uptime** information in **win_process_events**:
--------------------------------------------------------------
select wpe.action, wpe.cmdline, wpe.path, wpe.pid, wpe.parent_pid, ut.total_seconds AS uptime from **win_process_events** wpe JOIN **uptime** ut;

Example query to get **uptime** information in **win_socket_events**:
--------------------------------------------------------------
select wse.action, wse.eid, wse.local_address, wse.remote_address, wse.pid, wse.process_guid, ut.total_seconds AS uptime from **win_socket_events** wse JOIN **uptime** ut;

**Comment by devesh10s** [comment]
Thank you, that helped.

Closing this issue.
