### ISSUE TITLE
Windows event viewer logs not clearing automatically

### ISSUE THREAD

**Issue by sablearjun** [eclecticiq/osq-ext-bin#13]
When starting osqueryd with plgx_win_ext, extension starts logging events in windows event viewer. But after some time upon stopping the osqueryd windows event viewer logs are not automatically cleared. After manually clearing the logs from windows event viewer or using command `wevtutil cl `"PlgxRealTimeEvents/Log"``, then running osquery again. But now osqueryd doesnt log to wev. Running osqueryi after that starts logging into wev. Detailed screen recorded video is shared via a link here. 

https://drive.google.com/file/d/1PMbzFV-RF-LpAsRUuaLS5wioofWDJCzm/view?usp=sharing

**Comment by sablearjun** [comment]
[osquey run cmd.txt](https://github.com/eclecticiq/osq-ext-bin/files/11178458/osquey.run.cmd.txt)
[plgx-win-extension.log](https://github.com/eclecticiq/osq-ext-bin/files/11178459/plgx-win-extension.log)
[osquery_conf.txt](https://github.com/eclecticiq/osq-ext-bin/files/11178463/osquery_conf.txt)
[osquery_flags.txt](https://github.com/eclecticiq/osq-ext-bin/files/11178464/osquery_flags.txt)

.conf and .flags file is not supported for upload.

**Comment by atul-eiq** [comment]
Hi @sablearjun ,
Will look into it. In the meantime, can you please adjust the problem statement?

**Comment by atul-eiq** [comment]
Can you also attach osquery's verbose log messages as well?

**Comment by hyadav-eiq** [comment]
@sablearjun can you share the exact command lines you are using to run osquery as shell (osqueryi) VS osquery running as daemon?

**Comment by hyadav-eiq** [comment]
@sablearjun assuming that it's working now, can this ticket be closed?

**Comment by sablearjun** [comment]
@hyadav-eiq Thank you for the help. The issue is resolved after changing the configurations. This ticket can be closed. Thanks.

**Comment by hyadav-eiq** [comment]
Closing
